import {h, Fragment, mount, useMemo, useState} from './tiny-ui';
import {additives,candidateSeeds,palette} from './data/basementPalette';
import {additiveFromTotalPercent,formatVolume,mixHex,mixMany,scaleRecipe,scoreColor} from './lib/color';
import type {MixCandidate, PaintColor} from './types';
import './styles.css';

const nav=['Palette','Remix lab','Best options','Test recipe','Compare'];
const scoreLabels:Record<string,string>={restraint:'Usable change',sharkskin:'Sharkskin fit',sawMill:'Saw Mill fit',softness:'Chroma control',lightness:'Value balance',undertone:'Warm bridge'};

function PaintSwatch({paint}:{paint:PaintColor}){return <article className="paint-card"><div className="swatch" style={{background:paint.hex}}><span>{paint.hex}</span></div><div className="paint-copy"><div className="eyebrow">{paint.manufacturer} · {paint.code}</div><h3>{paint.name}</h3><p>{paint.hueFamily} · {paint.lightness}</p><dl><div><dt>Chroma</dt><dd>{paint.chroma}</dd></div><div><dt>Tendency</dt><dd>{paint.temperature}</dd></div><div><dt>Undertone</dt><dd>{paint.undertones}</dd></div></dl><div className="source"><b>{paint.verified?'Verified':'Estimated digital reference'}</b><br/>{paint.source}</div></div></article>}
function PaletteStrip({candidate}:{candidate:string}){return <div className="strip" aria-label="Palette comparison"><div style={{background:palette.sharkskin.hex}}>Sharkskin</div><div style={{background:candidate}}>Laundry</div><div style={{background:palette.sawMill.hex}}>Saw Mill</div></div>}
function BatchScaler({baseOz,additiveOz}:{baseOz:number;additiveOz:number}){return <div className="batch-grid">{[4,8,16].map(size=><div key={size}><b>{size} oz test base</b><strong>+ {formatVolume(scaleRecipe(baseOz,additiveOz,size))}</strong><span>additive · final {formatVolume(size+scaleRecipe(baseOz,additiveOz,size))}</span></div>)}</div>}
function HarmonyScore({scores}:{scores:MixCandidate['scores']}){return <div className="score"><div className="score-total"><strong>{scores.overall}</strong><span>advisory fit<br/>out of 100</span></div><div>{Object.entries(scoreLabels).map(([k,label])=><div className="meter" key={k}><span>{label}</span><i><b style={{width:`${scores[k as keyof typeof scores]}%`}}/></i><em>{scores[k as keyof typeof scores]}</em></div>)}</div></div>}
function RoomPreview({color,light}:{color:string;light:string}){return <div className={`room light-${light}`} style={{'--wall':color}}><div className="ceiling"/><div className="door"><div className="hall">Sharkskin</div></div><div className="shelf"><i/><i/><i/></div><div className="washer"><span/><b/></div><div className="dryer"><span/><b/></div><div className="counter"/><div className="accent">Saw Mill<br/>basket</div><div className="floor"/><small>Approximate {light==='warm'?'2700K warm':light==='neutral'?'3500K neutral':'5000K daylight'} preview</small></div>}
function Disclaimer(){return <aside className="disclaimer"><span>!</span><div><b>Direction, not a formula.</b> Screen color and OKLab interpolation do not predict pigment behavior. Base type, pigment load, tint chemistry, product line, sheen, wet/dry appearance, lighting, substrate and film thickness all change results. Test and dry a small batch first; combine only compatible chemistry, family, sheen and base.</div></aside>}

function App(){
 const [tab,setTab]=useState(0),[baseOz,setBaseOz]=useState(128),[additiveId,setAdditiveId]=useState('greige'),[addOz,setAddOz]=useState(10),[unit,setUnit]=useState<'oz'|'cups'|'percent'>('oz'),[custom,setCustom]=useState('#A89C89'),[light,setLight]=useState('neutral'),[compare,setCompare]=useState(0);
 const selected=additiveId==='custom'?{id:'custom',name:'Custom color',hex:custom,note:'User-entered screen color; compatibility unknown.'}:additives.find(a=>a.id===additiveId)!;
 const safeHex=/^#[0-9a-f]{6}$/i.test(selected.hex)?selected.hex:'#A89C89';
 const renderedOz=unit==='oz'?addOz:unit==='cups'?addOz*8:additiveFromTotalPercent(baseOz,Math.min(addOz,95));
 const simHex=mixHex(palette.viningIvy.hex,safeHex,baseOz,renderedOz);
 const candidates=useMemo(()=>candidateSeeds.map(seed=>{const parts=seed.parts.map(p=>({...p,hex:additives.find(x=>x.id===p.additiveId)!.hex}));const hex=mixMany(palette.viningIvy.hex,128,parts.map(p=>({hex:p.hex,oz:p.additiveOz})));return {...seed,hex,scores:scoreColor(hex,palette.viningIvy.hex,palette.sharkskin.hex,palette.sawMill.hex)}}),[]);
 const active=candidates[compare];
 return <><header><a className="brand" onClick={()=>setTab(0)}><i>PR</i><span>Paint Remix Lab<small>Personal color workshop</small></span></a><nav>{nav.map((n,i)=><button className={tab===i?'active':''} onClick={()=>setTab(i)} key={n}>{String(i+1).padStart(2,'0')}<span>{n}</span></button>)}</nav></header><main>
 {tab===0&&<section><div className="hero"><div><div className="eyebrow">Your basement · palette diagnosis</div><h1>Make the green feel<br/><em>meant to be here.</em></h1><p>Vining Ivy is a characterful cool blue-green. Your other rooms speak in quieter stone gray and warm, sawdust brown. The disconnect is mostly <b>chroma and temperature</b>—not hue alone.</p><button className="primary" onClick={()=>setTab(1)}>Open the remix lab <span>→</span></button></div><div className="hero-stack"><span style={{background:palette.sawMill.hex}}>Saw Mill</span><span style={{background:palette.viningIvy.hex}}>Vining Ivy</span><span style={{background:palette.sharkskin.hex}}>Sharkskin</span></div></div><div className="section-head"><div><div className="eyebrow">01 · Starting point</div><h2>Three colors, two conversations</h2></div><p>The goal is a bridge: keep Vining Ivy’s personality, lower its blue-green intensity, then borrow either Sharkskin’s softness or Saw Mill’s warmth.</p></div><div className="paint-grid"><PaintSwatch paint={palette.viningIvy}/><PaintSwatch paint={palette.sharkskin}/><PaintSwatch paint={palette.sawMill}/></div><div className="analysis"><b>Consultant’s read</b><p>Vining Ivy’s deeper, cooler chroma makes it feel like a separate jewel-toned scheme. The corrected inventory makes Gypsum, Ivory, and Crystal Crush the most useful softening tests; strong gold, mustard, and brown samples are higher-risk micro-dose experiments.</p><span>All displayed digital coordinates are editable estimates—not verified manufacturer values.</span></div><div className="inventory-head"><div><div className="eyebrow">On your shelf</div><h2>Corrected physical inventory</h2></div><p>Container maker and product stay separate from color specification ownership. Codes never override the label on the physical paint.</p></div><div className="inventory">{additives.filter(a=>a.owned).map(a=><article key={a.id}><i style={{background:a.hex}}/><div><b>{a.colorName}</b><span>{a.colorSpecification} · {a.digitalStatus} screen color</span></div><dl><dt>Physical paint</dt><dd>{a.physicalManufacturer} · {a.productLine}</dd><dt>Finish / base</dt><dd>{a.finishBase}</dd><dt>Available</dt><dd>{a.availableOz===128?'≈ 1 gallon':`${a.availableOz} oz sample`}</dd><dt>Color spec source</dt><dd>{a.specificationOwner}</dd></dl></article>)}</div></section>}
 {tab===1&&<section><div className="section-head"><div><div className="eyebrow">02 · Interactive experiment</div><h2>Remix without risking the gallon</h2></div><p>Explore perceptual screen blends, then carry only the ratio—not the promised color—into a small physical test.</p></div><div className="lab"><div className="controls"><label>Starting Vining Ivy <span>{baseOz.toFixed(0)} fl oz</span><input type="range" min="8" max="128" value={baseOz} onChange={e=>setBaseOz(+e.target.value)}/></label><div className="field"><label>Additive direction</label><select value={additiveId} onChange={e=>setAdditiveId(e.target.value)}>{additives.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}<option value="custom">Custom HEX</option></select></div>{additiveId==='custom'&&<div className="field"><label>Custom six-digit HEX</label><input value={custom} onChange={e=>setCustom(e.target.value)}/></div>}<div className="unit-tabs">{(['oz','cups','percent'] as const).map(u=><button onClick={()=>{setUnit(u);setAddOz(u==='oz'?8:u==='cups'?1:6)}} className={unit===u?'active':''} key={u}>{u==='oz'?'Ounces':u==='cups'?'Cups':'% total'}</button>)}</div><label>Amount <span>{addOz} {unit}</span><input type="range" min="0" max={unit==='percent'?30:unit==='cups'?4:32} step={unit==='cups' ? .125 : unit==='percent' ? .5 : .25} value={addOz} onChange={e=>setAddOz(+e.target.value)}/></label><div className="quick">{[4,8,12,16].map(v=><button onClick={()=>{setUnit('oz');setAddOz(v)}} key={v}>{v} oz</button>)}</div><p className="note">{selected.note}</p></div><div className="result"><div className="result-swatch" style={{background:simHex}}><div><span>Digital approximation</span><strong>{simHex}</strong></div></div><PaletteStrip candidate={simHex}/><div className="recipe"><div><span>Original base</span><b>{formatVolume(baseOz)}</b></div><div><span>Additive</span><b>{formatVolume(renderedOz)}</b></div><div><span>Total-mixture share</span><b>{(renderedOz/(baseOz+renderedOz)*100).toFixed(1)}% additive</b></div></div></div></div><div className="test-callout"><div><div className="eyebrow">Small-batch safety calculator</div><h3>Test this ratio before the gallon.</h3><p>These preserve additive : Vining Ivy base. Measure the base first, then add the listed amount.</p></div><BatchScaler baseOz={baseOz} additiveOz={renderedOz}/></div></section>}
 {tab===2&&<section><div className="section-head"><div><div className="eyebrow">03 · Ranked recommendations</div><h2>Every owned option, evaluated</h2></div><p>Editorial rank combines palette judgment, useful visible change, supply, and compatibility risk; the numerical score is a separate screen-color heuristic.</p></div><div className="candidate-grid">{candidates.map((c,i)=><article className="candidate" key={c.name}><div className="candidate-color" style={{background:c.hex}}><b>{String(i+1).padStart(2,'0')}</b><span>{c.hex}<small>simulated</small></span></div><div className="candidate-copy"><div className="eyebrow">{c.direction}</div><h3>{c.name}</h3><p>{c.rationale}</p><div className="chips"><span>{c.confidence} confidence</span>{c.parts.map(p=><span key={p.additiveId}>{additives.find(a=>a.id===p.additiveId)?.colorName}</span>)}</div><div className="relationships"><p><b>With Sharkskin</b>{c.sharkskinRelationship}</p><p><b>With Saw Mill</b>{c.sawMillRelationship}</p></div><div className="mini-recipe"><b>128 oz base</b><span>{c.parts.map(p=>`+ ${p.additiveOz} oz ${additives.find(a=>a.id===p.additiveId)?.colorName}`).join(' ')}</span><b>8 oz test</b><span>{c.parts.map(p=>`+ ${scaleRecipe(128,p.additiveOz,8).toFixed(2)} oz ${additives.find(a=>a.id===p.additiveId)?.colorName}`).join(' ')}</span></div><details><summary>Screen-color score {c.scores.overall} →</summary><HarmonyScore scores={c.scores}/><p className="risk"><b>Watch:</b> {c.risks}</p></details></div></article>)}</div></section>}
 {tab===3&&<section><div className="test-hero"><div><div className="eyebrow">04 · Physical test plan</div><h2>Small cup.<br/>Big insurance.</h2><p>Make the 8 oz-base recipes below, coat movable boards twice, and judge only after a full dry-down in the actual room.</p></div><div className="warning-card"><b>Never alter all 128 ounces first.</b><span>RGB and HEX are not paint formulas. A physical dry sample is the decision point.</span></div></div><div className="top-tests">{candidates.slice(0,3).map((c,i)=><article key={c.name}><span>TEST 0{i+1}</span><h3>{c.name}</h3><div className="pour"><i style={{background:palette.viningIvy.hex}}/><b>8.00</b><em>oz Vining Ivy</em>{c.parts.map(p=><Fragment key={p.additiveId}><strong>+</strong><i style={{background:additives.find(a=>a.id===p.additiveId)?.hex}}/><b>{scaleRecipe(128,p.additiveOz,8).toFixed(2)}</b><em>oz {additives.find(a=>a.id===p.additiveId)?.colorName}</em></Fragment>)}</div><p>Exact base-relative recipe · descriptive result, not a PPG formula</p></article>)}</div><ol className="steps"><li><b>Label + measure</b><span>Stir first. Use graduated tools; record every increment.</span></li><li><b>Mix + inspect</b><span>Stop for curdling, separation, texture, or sheen mismatch.</span></li><li><b>Make boards</b><span>Two coats on primed movable boards; keep an original control.</span></li><li><b>Dry + observe</b><span>Compare for 48 hours beside both basement colors in real light.</span></li></ol></section>}
 {tab===4&&<section><div className="section-head"><div><div className="eyebrow">05 · Context check</div><h2>See the relationships, not a promise</h2></div><p>Lighting filters are intentionally subtle and approximate. Screens cannot model metamerism or wet-to-dry shift.</p></div><div className="compare-controls"><select value={compare} onChange={e=>setCompare(+e.target.value)}>{candidates.map((c,i)=><option value={i} key={c.name}>{String(i+1).padStart(2,'0')} · {c.name}</option>)}</select><div className="unit-tabs">{[['warm','2700K'],['neutral','3500K'],['day','5000K']].map(([v,n])=><button className={light===v?'active':''} onClick={()=>setLight(v)} key={v}>{n}</button>)}</div></div><div className="compare-layout"><div><RoomPreview color={active.hex} light={light}/><PaletteStrip candidate={active.hex}/></div><div className="compare-copy"><div className="candidate-dot" style={{background:active.hex}}/><div className="eyebrow">Rank {compare+1} · {active.direction}</div><h2>{active.name}</h2><p>{active.rationale}</p><div className="comparison-original"><span style={{background:palette.viningIvy.hex}}/>Original {palette.viningIvy.hex}<b>→</b><span style={{background:active.hex}}/>Candidate {active.hex}</div><HarmonyScore scores={active.scores}/></div></div></section>}
 </main><Disclaimer/><footer><span>PAINT REMIX LAB · PERSONAL USE ONLY</span><span>No official PPG formulas · estimates are labeled</span></footer></>;
}
mount(document.getElementById('root')!, App);
